teams:
  - name: lf-staff
    maintainers:
      - ryjones
  - name: solang-admins
    maintainers:
      - seanyoung
    members:
      - xermicus
  - name: solang-aqd-committers
    maintainers:
      - tareknaser
  - name: solang-committers
    maintainers:
      - seanyoung
    members:
      - LucasSte
      - salaheldinsoliman
      - xermicus
  - name: solang-contributors
    maintainers:
      - seanyoung
    members:
      - LucasSte
      - salaheldinsoliman
      - tareknaser
      - xermicus
  - name: solang-triage
    maintainers:
      - seanyoung
repositories:
  - name: governance
    teams:
      lf-staff: admin
      solang-admins: write
    visibility: public
  - name: homebrew-solang
    teams:
      solang-admins: admin
      solang-committers: maintain
      solang-contributors: read
    visibility: public
  - name: solang-aqd
    teams:
      solang-admins: admin
      solang-aqd-committers: maintain
      solang-committers: maintain
      solang-contributors: read
    visibility: public
  - name: solang-substrate-ci
    teams:
      solang-admins: admin
      solang-committers: maintain
      solang-contributors: read
    visibility: public
  - name: solang
    teams:
      solang-admins: admin
      solang-committers: maintain
      solang-contributors: read
      solang-triage: triage
    visibility: public
  - name: solang-llvm
    teams:
      solang-admins: admin
      solang-committers: maintain
      solang-contributors: read
    visibility: public
