teams:
  - name: lf-staff
    maintainers:
      - ryjones
  - name: solang-admins
    maintainers:
      - ryjones
    members:
      - seanyoung
      - xermicus
  - name: solang-aqd-committers
    maintainers:
      - tareknaser
  - name: solang-committers
    maintainers:
      - ryjones
    members:
      - seanyoung
      - LucasSte
      - salaheldinsoliman
      - xermicus
  - name: solang-contributors
    maintainers:
      - ryjones
    members:
      - LucasSte
      - salaheldinsoliman
      - seanyoung
      - tareknaser
      - xermicus
  - name: solang-triage
    maintainers:
      - ryjones
    members:
      - seanyoung
repositories:
  - name: governance
    teams:
      lf-staff: admin
      solang-admins: write
    visibility: public
  - name: homebrew-solang
    teams:
      solang-admins: admin
      solang-committers: maintain
      solang-contributors: read
    visibility: public
  - name: solang-aqd
    teams:
      solang-admins: admin
      solang-aqd-committers: maintain
      solang-committers: maintain
      solang-contributors: read
    visibility: public
  - name: solang-substrate-ci
    teams:
      solang-admins: admin
      solang-committers: maintain
      solang-contributors: read
    visibility: public
